'Autor: Rupert Wieser -- Naotilus -- 202202122'

class Param():
    FORMAT_TELEGRAFFRAMESEPERATOR = "%s\n"
    FORMAT_TELEGRAFFRAMESTRUCT = "%s,instance=%s %s=%f %.0f"
    FORMAT_TELEGRAFFRAMESTRUCT2 = "%s,instance=%s %s="
    NAME_GET = "GET"
    NAME_POST = "POST"
    NAME_RESULTS = "results"
    NAME_LASTTIME = "last_timestamp"
    NAME_INTERVAL = "interval"
    NAME_VALUE = "value"
    NAME_VARIABLE = "variable"
    NAME_TIMESTAP = "timestamp"
    NAME_HOST = "host"
    NAME_COUNT = "count"
    NAME_WEBAUTH = "Authorization"
    NAME_TELEGRAF = "telegraf"
    NAME_UTF8 = "utf-8"
    NAME_TOKENAC = "accessToken"
    NAME_TOKENRE = "refreshToken"
    NAME_COOKIE = "Cookie"
    NAME_EMAIL = "email"
    NAME_PASSWD = "password"
    NAME_PAYLOAD = "payload"
    NAME_TYPE = "type"
    NAME_CHANNEL = "channel"
    NAME_TRANSFERCHANNELS = "transfer_channels"
    NAME_POINT = "point"
    NAME_ASSET = "asset"
    NAME_INSTANCE = "instance"
    NAME_SERIES = "series"
    NAME_CONTENT_HEADER = "Content-Type"
    NAME_ASSET_ID = "_asset"
    NAME_NAME = "name"
    NAME_DESCRIPTION = "description"
    NAME_GEOLOCATION = "geolocation"
    NAME_ID_ID = "_id"
    NAME_INPUT_ID = "_input"
    NAME_RELATION_ID = "_relation"
