'Autor: Rupert Wieser -- Naotilus -- 202202122'

class Param():
    FORMAT_TELEGRAFFRAMESEPERATOR = "%s\n"
    FORMAT_TELEGRAFFRAMESTRUCT = "%s,instance=%s %s=%f %.0f"
    NAME_GET = "GET"
    NAME_POST = "POST"
    NAME_LASTTIME = "last_timestamp"
    NAME_INTERVAL = "interval"
    NAME_VALUE = "value"
    NAME_VARIABLE = "variable"
    NAME_TIMESTAP = "timestamp"
    NAME_HOST = "host"
    NAME_COUNT = "count"
    NAME_WEBAUTH = "Authorization"
    NAME_TELEGRAF = "telegraf"
    NAME_UTF8 = "utf-8"
    NAME_TOKENAC = "accessToken"
    NAME_TOKENRE = "refreshToken"
    NAME_COOKIE = "Cookie"
    NAME_EMAIL = "email"
    NAME_PASSWD = "password"
    NAME_PAYLOAD = "payload"
    NAME_TYPE = "type"
    NAME_CHANNEL = "channel"
    NAME_TRANSFERCHANNELS = "connection"
    NAME_POINT = "point"
    NAME_ASSET = "asset"
    NAME_INSTANCE = "instance"
    NAME_SERIES = "series"